project:
  type: website

theme:
  dark: _assets/darkly.scss
  light: _assets/flatly.scss

# jupyter: julia-1.10

website:
  title: "likan.org"
  favicon: _assets/logo.png
  repo-url: https://github.com/likanzhan/likan.org
  repo-actions: [edit, issue]
  navbar:
    background: "light"
    left:
      - file: about-en.md
        text: About
      - file: cv-en.md
        text: CV
      - url: http://sapere-aude.group
        text: Team
      - file: about-zh.md
        text: 关于
      - file: cv-zh.md
        text: 简历
  page-footer: 
    left: "Copyright 2024-, Likan Zhan" 
    right: 
      - icon: github
        href: https://github.com/likanzhan

format:
  pdf:
    documentclass: ctexbook
    toc: false
    classoption: 
      - UTF8
    papersize: a4
    linestretch: 1
    include-in-header:
    - text: |
        \usepackage{_assets/CV-LaTeX-Preamble}