project:
  type: website

theme:
  dark: darkly
  light: flatly

website:
  title: "likan.org"
  navbar:
    background: "light"
    left:
      - file: about-en.md
        text: About
      - file: cv-en.md
        text: CV
      - url: http://sapere-aude.group
        text: Team
      - file: about-zh.md
        text: 关于
      - file: cv-zh.md
        text: 简历