project:
  type: website

theme:
  dark: darkly
  light: flatly

website:
  title: "likan.org"
  navbar:
    background: "light"
    left:
      - file: about-en.md
        text: About
      - file: about-zh.md
        text: 关于

format:
  html:
    css: styles.css
    toc: true



