on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up Python and Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
        run: pip install jupyter
        run: pip install -r _assets/requirements.txt

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
        uses: julia-actions/cache@v1
        uses: julia-actions/julia-buildpkg@v1

      - name: Set up R, TinyTeX, and install packages
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
        uses: r-lib/actions/setup-tinytex@v2
        run: |
          tlmgr install titlesec
          tlmgr list --only-installed

      - name: Set up Quarto, render and publish
        uses: quarto-dev/quarto-actions/setup@v2
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}